### ISSUE TITLE
error with autonumber function

### ISSUE THREAD

**Issue by lucatrev90** [sandrotosi/puddletag#3]
```
puddletag Version: 2.0.0
Locale: it_IT
Traceback (most recent call last):
  File "/home/utonto/Scaricati/source/puddlestuff/puddleobjects.py", line 2325, in run
    self.retval = self.command()
  File "/home/utonto/Scaricati/source/puddlestuff/puddleobjects.py", line 870, in threadfunc
    temp = next(f)
  File "/home/utonto/Scaricati/source/puddlestuff/puddletag.py", line 750, in func
    for row, f in izip(rows, tagiter):
  File "/home/utonto/Scaricati/source/puddlestuff/mainwin/funcs.py", line 419, in tagiter
    val = function(rowtags.get(field, u''), rowtags, state, r_tags=f)
  File "/home/utonto/Scaricati/source/puddlestuff/findfunc.py", line 851, in runFunction
    return func(**topass)
  File "/home/utonto/Scaricati/source/puddlestuff/functions.py", line 102, in autonumbering
    tracknum = state['autonumbering'][index]
KeyError: 2
```

**Comment by sandrotosi** [comment]
@lucatrev90 are you 100% sure you're using my branch (`pyqt5+py3`) for your tests? I am not finally able to replicate this traceback, only after i needed to fix several python2->python3 issues (str vs bytes stuff) so i'm wondering if you're not actually running puddletag via python2?

**Comment by lucatrev90** [comment]
yep. i'm on debian sid
```
utonto@inspiron5520:~$ PYTHONPATH=source/ ./puddletag-pyqt5-py3/source/puddletag
puddletag Version: 2.0.0
Locale: it_IT
Traceback (most recent call last):
  File "/home/utonto/puddletag-pyqt5-py3/source/puddlestuff/puddleobjects.py", line 2325, in run
    self.retval = self.command()
  File "/home/utonto/puddletag-pyqt5-py3/source/puddlestuff/puddleobjects.py", line 870, in threadfunc
    temp = next(f)
  File "/home/utonto/puddletag-pyqt5-py3/source/puddlestuff/puddletag.py", line 750, in func
    for row, f in izip(rows, tagiter):
  File "/home/utonto/puddletag-pyqt5-py3/source/puddlestuff/mainwin/funcs.py", line 419, in tagiter
    val = function(rowtags.get(field, u''), rowtags, state, r_tags=f)
  File "/home/utonto/puddletag-pyqt5-py3/source/puddlestuff/findfunc.py", line 851, in runFunction
    return func(**topass)
  File "/home/utonto/puddletag-pyqt5-py3/source/puddlestuff/functions.py", line 102, in autonumbering
    tracknum = state['autonumbering'][index]
KeyError: 2
Annullato

```
```
utonto@inspiron5520:~$ sudo apt list --installed | grep python
[sudo] password di utonto: 

WARNING: apt does not have a stable CLI interface. Use with caution in scripts.

libpython3-stdlib/unstable,now 3.8.2-3 amd64 [installato, automatico]
libpython3.8-minimal/unstable,now 3.8.3-1 amd64 [installato, automatico]
libpython3.8-stdlib/unstable,now 3.8.3-1 amd64 [installato, automatico]
libpython3.8/unstable,now 3.8.3-1 amd64 [installato, automatico]
python3-cairo/unstable,now 1.16.2-3 amd64 [installato, automatico]
python3-certifi/unstable,now 2020.4.5.1-1 all [installato, automatico]
python3-chardet/unstable,now 3.0.4-7 all [installato, automatico]
python3-configobj/unstable,now 5.0.6-4 all [installato]
python3-cups/unstable,now 1.9.73-3+b1 amd64 [installato, automatico]
python3-cupshelpers/unstable,now 1.5.12-1 all [installato, automatico]
python3-dbus/unstable,now 1.2.16-2 amd64 [installato, automatico]
python3-gi-cairo/unstable,now 3.36.0-3 amd64 [installato, automatico]
python3-gi/unstable,now 3.36.0-3 amd64 [installato, automatico]
python3-idna/unstable,now 2.9-1 all [installato, automatico]
python3-minimal/unstable,now 3.8.2-3 amd64 [installato, automatico]
python3-mutagen/unstable,now 1.44.0-1 all [installato]
python3-pkg-resources/unstable,now 46.1.3-1 all [installato, automatico]
python3-pyparsing/unstable,now 2.4.7-1 all [installato]
python3-pyqt5.qtsvg/unstable,now 5.14.2+dfsg-1+b1 amd64 [installato]
python3-pyqt5/unstable,now 5.14.2+dfsg-1+b1 amd64 [installato]
python3-requests/unstable,now 2.23.0+dfsg-2 all [installato, automatico]
python3-sip/unstable,now 4.19.22+dfsg-1+b1 amd64 [installato, automatico]
python3-six/unstable,now 1.15.0-1 all [installato]
python3-talloc/unstable,now 2.3.0-5 amd64 [installato, automatico]
python3-urllib3/unstable,now 1.25.9-1 all [installato, automatico]
python3.8-minimal/unstable,now 3.8.3-1 amd64 [installato, automatico]
python3.8/unstable,now 3.8.3-1 amd64 [installato, automatico]
python3/unstable,now 3.8.2-3 amd64 [installato]

```

**Comment by sandrotosi** [comment]
ok i just wanted to make sure

and yes, i'm able to replicate it, and i'm working on it (for now i'm just trying to figure out what the code _wants_ to do, then i'll eventually fix it :) )

**Comment by sandrotosi** [comment]
ok, i've added a few fixes for code _around_ the autonumbering feature at https://github.com/sandrotosi/puddletag/commit/4c2a8e31268ba9e2cd51a0337f32ca2ea1c0e856, but i could not come up with a fix for the actual autonumbering feature: the code is too cumbersome and i'm unable to understand his behaviour

**Comment by audiomuze** [comment]
> ok, i've added a few fixes for code _around_ the autonumbering feature at [4c2a8e3](https://github.com/sandrotosi/puddletag/commit/4c2a8e31268ba9e2cd51a0337f32ca2ea1c0e856), but i could not come up with a fix for the actual autonumbering feature: the code is too cumbersome and i'm unable to understand its behaviour

The autonumbering feature is supposed to be able to number tracks in sequence, and behaves differently depending on what it finds in the selection and options a user selects in the dialogue screen that's presented when you invoke autonumbering. I'll need to play with it in the py2.x release to remember it's various behaviours, one of which was to restart numbering at 1 for every change in discnumber.  I could try find the discussion Keith and I had at the time re what we had landed on as a functional spec.

**Comment by audiomuze** [comment]
Perhaps the best way to illustrate is by way of example, given these files:
![image](https://user-images.githubusercontent.com/6852511/86091550-00db5b00-baa4-11ea-9e54-098bdb30bfde.png)

And these settings in the dialogue box:
![image](https://user-images.githubusercontent.com/6852511/86091626-1d779300-baa4-11ea-92ee-d83706558e2b.png)

The result looks like this:
![image](https://user-images.githubusercontent.com/6852511/86091753-557ed600-baa4-11ea-9eb3-a8e15cabbf30.png)

puddletag has in effect added a discnumber tag to all files in each folder, incrementing discnumber only on change in __dirpath

If I now wanted to automatically number all TRACKS, incrementing by 1 and restarting TRACK number at 1 for every change in __dirpath, I'd set the dialogue box as follows:

![image](https://user-images.githubusercontent.com/6852511/86092171-0be2bb00-baa5-11ea-9903-fd360ef706ed.png)

So to summarise:

- output field must be set to the field you want written by the Autonumbering function
- Increase counter only on group change should be turned on for writing out discnumber, but turned off if trying to number tracks.

The Group tracks using pattern setting enables a user to define a pattern by which to group tracks.  It's an actual pattern that will be evaluated. So "%fieldname1% - %fieldname2%" or "%fieldname1%%fieldname2%" ... doesn't really matter, the pattern is evaluated as defined and on each change in pattern the grouping will be considered to be different.

So you could for example have two or more albums that form part of a boxset all stored in a single folder, with each track tagged with its year and and track number.  If you wanted to add discnumbers to that you could sort by track, then by year, then run the Autonumbering wizard and use %year% as the pattern triggering an increment in discnumber as the output field.  Whether by  year sorting of the albums corresponds with discnumber in the box set is another matter. but you get the idea.


It's probably a good idea to rename the setting "Restart numbering at each directory group" to a more descriptive "Restart numbering at each change in grouping pattern"
