### ISSUE TITLE
Mass Tagging window produces a traceback

### ISSUE THREAD

**Issue by sandrotosi** [sandrotosi/puddletag#4]
```
Traceback (most recent call last):
  File "puddletag/source/puddlestuff/puddleobjects.py", line 2325, in run
    self.retval = self.command()
  File "puddletag/source/puddlestuff/masstag/dialogs.py", line 645, in run_masstag
    ret = match_files(files, retrieved,
  File "puddletag/source/puddlestuff/masstag/__init__.py", line 258, in match_files
    replace_tracknumbers(files, tracks)
  File "puddletag/source/puddlestuff/masstag/__init__.py", line 488, in replace_tracknumbers
    files = sorted(files, cmp=natcasecmp,
TypeError: 'cmp' is an invalid keyword argument for sort()
Aborted
```

i started trying to fix it, but i cant figure out what [that code](https://github.com/sandrotosi/puddletag/blob/pyqt5%2Bpy3/source/puddlestuff/masstag/__init__.py#L488-L494)'s supposed to do

**Comment by blueblots** [comment]
I made some changes on my own fork that prevents it from crashing but it still crashes under some scenarios, like this https://github.com/blueblots/puddletag/issues/2

**Comment by sandrotosi** [comment]
good, one step closer! :)
