### ISSUE TITLE
Freedb tag lookup throws NameError: name 'audioinfo' is not defined

### ISSUE THREAD

**Issue by audiomuze** [sandrotosi/puddletag#43]
```
$ export QT_QPA_PLATFORMTHEME=qt5ct && /home/x/github/pt3/puddletag/source/puddletag .
puddletag Version: 2.0.0
Locale: en_US
Traceback (most recent call last):
  File "/home/x/github/pt3/puddletag/source/puddlestuff/webdb.py", line 867, in search
    return tag_source_search(self.curSource, group, files)
  File "/home/x/github/pt3/puddletag/source/puddlestuff/webdb.py", line 558, in tag_source_search
    albums = ts.search(primary, group[primary])
  File "/home/x/github/pt3/puddletag/source/puddlestuff/tagsources/freedb.py", line 188, in search
    results = search(files)
  File "/home/x/github/pt3/puddletag/source/puddlestuff/tagsources/freedb.py", line 143, in search
    discid = calculate_discid(tracks)
  File "/home/x/github/pt3/puddletag/source/puddlestuff/tagsources/freedb.py", line 33, in calculate_discid
    lengths = [audioinfo.lnglength(to_string(song['__length']))
  File "/home/x/github/pt3/puddletag/source/puddlestuff/tagsources/freedb.py", line 33, in <listcomp>
    lengths = [audioinfo.lnglength(to_string(song['__length']))
NameError: name 'audioinfo' is not defined

```

**Comment by blueblots** [comment]
I have a fix for this in https://github.com/sandrotosi/puddletag/pull/34 but I'm considering closing it because of freedb shutting down. Is the fix still necessary?

**Comment by audiomuze** [comment]
I was under the impression that gnudb is a drop in replacement so the freedb plugin should probably be modified to to work with it.  http://www.gnudb.org/

**Comment by sandrotosi** [comment]
It has already been udpated to gnudb.org with https://github.com/sandrotosi/puddletag/pull/36 -- @blueblots if you want to rebase and submit the fix for the  traceback in your PR, I'd be happy to review it!

**Comment by sandrotosi** [comment]
vixed via #34
