### ISSUE TITLE
Acoustid lookup throws RuntimeError: dictionary changed size during iteration

### ISSUE THREAD

**Issue by audiomuze** [sandrotosi/puddletag#44]
```
$ export QT_QPA_PLATFORMTHEME=qt5ct && /home/x/github/pt3/puddletag/source/puddletag .
puddletag Version: 2.0.0
Locale: en_US
Traceback (most recent call last):
  File "/home/x/github/pt3/puddletag/source/puddlestuff/webdb.py", line 867, in search
    return tag_source_search(self.curSource, group, files)
  File "/home/x/github/pt3/puddletag/source/puddlestuff/webdb.py", line 560, in tag_source_search
    ret.extend(albums)
  File "/home/x/github/pt3/puddletag/source/puddlestuff/tagsources/acoust_id.py", line 226, in retrieve_album_info
    info, new_tracks = retrieve_album(album['mbrainz_album_id'])
  File "/home/x/github/pt3/puddletag/source/puddlestuff/tagsources/musicbrainz.py", line 367, in retrieve_album
    return parse_album(data)
  File "/home/x/github/pt3/puddletag/source/puddlestuff/tagsources/musicbrainz.py", line 130, in parse_album
    return parse_release(release_node)
  File "/home/x/github/pt3/puddletag/source/puddlestuff/tagsources/musicbrainz.py", line 294, in parse_release
    tracks.extend(parse_track_list(medium))
  File "/home/x/github/pt3/puddletag/source/puddlestuff/tagsources/musicbrainz.py", line 320, in parse_track_list
    for k, v in track.items():
RuntimeError: dictionary changed size during iteration

```

**Comment by sandrotosi** [comment]
Fixed via #46
