### ISSUE TITLE
Musicbrainz lookup throws RuntimeError: dictionary changed size during iteration

### ISSUE THREAD

**Issue by audiomuze** [sandrotosi/puddletag#46]
```
$ export QT_QPA_PLATFORMTHEME=qt5ct && /home/x/github/pt3/puddletag/source/puddletag .
puddletag Version: 2.0.0
Locale: en_US
Traceback (most recent call last):
  File "/home/x/github/pt3/puddletag/source/puddlestuff/releasewidget.py", line 465, in retrieval_func
    return self.tagsource.retrieve(item.itemData)
  File "/home/x/github/pt3/puddletag/source/puddlestuff/tagsources/musicbrainz.py", line 600, in retrieve
    ret = retrieve_album(album_id)
  File "/home/x/github/pt3/puddletag/source/puddlestuff/tagsources/musicbrainz.py", line 367, in retrieve_album
    return parse_album(data)
  File "/home/x/github/pt3/puddletag/source/puddlestuff/tagsources/musicbrainz.py", line 130, in parse_album
    return parse_release(release_node)
  File "/home/x/github/pt3/puddletag/source/puddlestuff/tagsources/musicbrainz.py", line 294, in parse_release
    tracks.extend(parse_track_list(medium))
  File "/home/x/github/pt3/puddletag/source/puddlestuff/tagsources/musicbrainz.py", line 320, in parse_track_list
    for k, v in track.items():
RuntimeError: dictionary changed size during iteration

```

**Comment by sandrotosi** [comment]
isnt this #44?

**Comment by audiomuze** [comment]
> isnt this #44?

I suspect its the same issue, but as they're different tag sources I raised it for both.

**Comment by sandrotosi** [comment]
@infidelus ^^

**Comment by infidelus** [comment]
Bingo!  Working.  Time to get the led out! :)
