### ISSUE TITLE
Musicbraniz masstagging: Core dumped

### ISSUE THREAD

**Issue by audiomuze** [sandrotosi/puddletag#59]
Traceback (most recent call last):
  File "/home/x/github/pt3/puddletag/source/puddlestuff/tagsources/__init__.py", line 184, in urlopen
    page = urllib.request.build_opener().open(request)
  File "/usr/lib/python3.8/urllib/request.py", line 531, in open
    response = meth(req, response)
  File "/usr/lib/python3.8/urllib/request.py", line 640, in http_response
    response = self.parent.error(
  File "/usr/lib/python3.8/urllib/request.py", line 569, in error
    return self._call_chain(*args)
  File "/usr/lib/python3.8/urllib/request.py", line 502, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.8/urllib/request.py", line 649, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 404: NOT FOUND

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/x/github/pt3/puddletag/source/puddlestuff/tagsources/musicbrainz.py", line 377, in retrieve_cover_links
    data, code = urlopen(url, code=True)
  File "/home/x/github/pt3/puddletag/source/puddlestuff/tagsources/__init__.py", line 202, in urlopen
    raise RetrievalError(msg, e.code)
puddlestuff.tagsources.RetrievalError: HTTP Error 404: NOT FOUND

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/x/github/pt3/puddletag/source/puddlestuff/tagsources/musicbrainz.py", line 612, in retrieve_covers
    image = retrieve_front_cover(album_id)
  File "/home/x/github/pt3/puddletag/source/puddlestuff/tagsources/musicbrainz.py", line 427, in retrieve_front_cover
    data = retrieve_cover_links(album_id, "front")
  File "/home/x/github/pt3/puddletag/source/puddlestuff/tagsources/musicbrainz.py", line 380, in retrieve_cover_links
    raise RetrievalError(translate("MusicBrainz",
puddlestuff.tagsources.RetrievalError: No images exist for this album.

Traceback (most recent call last):
  File "/home/x/github/pt3/puddletag/source/puddlestuff/puddleobjects.py", line 2383, in run
    self.retval = self.command()
  File "/home/x/github/pt3/puddletag/source/puddlestuff/masstag/dialogs.py", line 644, in run_masstag
    masstag(mtp, files, self.__flag, search_error,
  File "/home/x/github/pt3/puddletag/source/puddlestuff/masstag/__init__.py", line 447, in masstag
    result = tsp.retrieve(matches[0], errors=tsp_error_func)
  File "/home/x/github/pt3/puddletag/source/puddlestuff/masstag/__init__.py", line 705, in retrieve
    self.result = Result(*results)
  File "/home/x/github/pt3/puddletag/source/puddlestuff/masstag/__init__.py", line 623, in __init__
    self.info = {} if info is None else info
  File "/home/x/github/pt3/puddletag/source/puddlestuff/masstag/__init__.py", line 633, in _set_info
    self.merged = [merge_track(a, value) for a in self.__tracks]
  File "/home/x/github/pt3/puddletag/source/puddlestuff/masstag/__init__.py", line 633, in <listcomp>
    self.merged = [merge_track(a, value) for a in self.__tracks]
  File "/home/x/github/pt3/puddletag/source/puddlestuff/masstag/__init__.py", line 358, in merge_track
    track[key] = info[key][::]
TypeError: unhashable type: 'slice'
Aborted (core dumped)

**Comment by sandrotosi** [comment]
@audiomuze can you also explain exactly what you were doing, what you had selected, what artist/album/song you were working on etc etc? just a traceback is not enough (but helpful!).

**Comment by audiomuze** [comment]
Steps to reproduce:

- Load a folder with **one or more** subdirs containing albums.
- Select all files
- Sort files by __filename and then __dirpath to get correct track sequencing by album bty clicking on the respective column headers
- Select Massgtagging with Musicbrainz as the tag source
- Select the Masstagging Search button
- From testing the underlying album and/or file type doesn't alter the outcome.

**Multiple album selection:**
```
$ export QT_QPA_PLATFORMTHEME=qt5ct && /home/x/github/pt3/puddletag/source/puddletag .
puddletag Version: 2.0.0
Locale: en_US
:insertStarting search for: <br />artist=<b>Spirit Adrift</b> <br />album=<b>Curse of Conception</b><br />
<b>Polling: MusicBrainz</b>
<b>2</b> results found.
<b>2</b> possibly matching albums found.
Retrieving matching album. <b>Spirit Adrift - Curse of Conception</b>
Traceback (most recent call last):
  File "/home/x/github/pt3/puddletag/source/puddlestuff/puddleobjects.py", line 2383, in run
    self.retval = self.command()
  File "/home/x/github/pt3/puddletag/source/puddlestuff/masstag/dialogs.py", line 644, in run_masstag
    masstag(mtp, files, self.__flag, search_error,
  File "/home/x/github/pt3/puddletag/source/puddlestuff/masstag/__init__.py", line 447, in masstag
    result = tsp.retrieve(matches[0], errors=tsp_error_func)
  File "/home/x/github/pt3/puddletag/source/puddlestuff/masstag/__init__.py", line 705, in retrieve
    self.result = Result(*results)
  File "/home/x/github/pt3/puddletag/source/puddlestuff/masstag/__init__.py", line 623, in __init__
    self.info = {} if info is None else info
  File "/home/x/github/pt3/puddletag/source/puddlestuff/masstag/__init__.py", line 633, in _set_info
    self.merged = [merge_track(a, value) for a in self.__tracks]
  File "/home/x/github/pt3/puddletag/source/puddlestuff/masstag/__init__.py", line 633, in <listcomp>
    self.merged = [merge_track(a, value) for a in self.__tracks]
  File "/home/x/github/pt3/puddletag/source/puddlestuff/masstag/__init__.py", line 358, in merge_track
    track[key] = info[key][::]
TypeError: unhashable type: 'slice'
Aborted (core dumped)
```
**Single album selection:**
```
$ export QT_QPA_PLATFORMTHEME=qt5ct && /home/x/github/pt3/puddletag/source/puddletag .
puddletag Version: 2.0.0
Locale: en_US
:insertStarting search for: <br />artist=<b>Thin Lizzy</b> <br />album=<b>BBC Radio One: Live in Concert</b><br />
<b>Polling: MusicBrainz</b>
Traceback (most recent call last):
  File "/home/x/github/pt3/puddletag/source/puddlestuff/puddleobjects.py", line 2383, in run
    self.retval = self.command()
  File "/home/x/github/pt3/puddletag/source/puddlestuff/masstag/dialogs.py", line 644, in run_masstag
    masstag(mtp, files, self.__flag, search_error,
  File "/home/x/github/pt3/puddletag/source/puddlestuff/masstag/__init__.py", line 427, in masstag
    for matches, results, tsp in mtp.search(files, errors=mtp_error_func):
  File "/home/x/github/pt3/puddletag/source/puddlestuff/masstag/__init__.py", line 589, in search
    results = profile.search(files)
  File "/home/x/github/pt3/puddletag/source/puddlestuff/masstag/__init__.py", line 730, in search
    self.results = [Result(*x) for x in tag_source.search(search_value, files[search_value])]
  File "/home/x/github/pt3/puddletag/source/puddlestuff/masstag/__init__.py", line 730, in <listcomp>
    self.results = [Result(*x) for x in tag_source.search(search_value, files[search_value])]
  File "/home/x/github/pt3/puddletag/source/puddlestuff/masstag/__init__.py", line 623, in __init__
    self.info = {} if info is None else info
  File "/home/x/github/pt3/puddletag/source/puddlestuff/masstag/__init__.py", line 633, in _set_info
    self.merged = [merge_track(a, value) for a in self.__tracks]
  File "/home/x/github/pt3/puddletag/source/puddlestuff/masstag/__init__.py", line 633, in <listcomp>
    self.merged = [merge_track(a, value) for a in self.__tracks]
  File "/home/x/github/pt3/puddletag/source/puddlestuff/masstag/__init__.py", line 358, in merge_track
    track[key] = info[key][::]
TypeError: unhashable type: 'slice'
Aborted (core dumped)
```

**Comment by audiomuze** [comment]
In case it's relevant, here's the musicbrainz masstagging profile I used:

![image](https://user-images.githubusercontent.com/6852511/89982178-83476500-dc75-11ea-9fa1-3f4f2e20e5b9.png)
