### ISSUE TITLE
Button missing in error dialogue box

### ISSUE THREAD

**Issue by audiomuze** [sandrotosi/puddletag#62]
I deliberately invoked an error condition by having two sub-folders with identical tracks and metadata content but differing folder names.  Loaded them and then ran an action that leverages the tag values to rename files and the sub-folders, causing a clash in target folder name for the second album.  puddletag threw the error dialogue as expected, but the "No" button is missing when it presents the "Do you want to continue?" dialogue:

![image](https://user-images.githubusercontent.com/6852511/90330745-89a84a80-dfaf-11ea-9e8c-0c9e7a83639f.png)

```
$ export QT_QPA_PLATFORMTHEME=qt5ct && /home/x/github/pt3/puddletag/source/puddletag .
puddletag Version: 2.0.0
Locale: en_US
Traceback (most recent call last):
  File "/home/x/github/pt3/puddletag/source/puddlestuff/util.py", line 84, in rename_dir
    os.renames(olddir, newdir)
  File "/usr/lib/python3.8/os.py", line 270, in renames
    rename(old, new)
OSError: [Errno 39] Directory not empty: '/mnt/sdb1/2tag/Copy (1) Blue Öyster Cult - 45th Anniversary Live in London [2444.1 kHz]' -> '/mnt/sdb1/2tag/Blue Öyster Cult - 45th Anniversary Live in London [2444.1 kHz]'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/x/github/pt3/puddletag/source/puddlestuff/puddletag.py", line 740, in func
    update = setRowData(row, f, undo=True)
  File "/home/x/github/pt3/puddletag/source/puddlestuff/tagmodel.py", line 1102, in setRowData
    undo_val = write(audio, tags, self.saveModification, justrename)
  File "/home/x/github/pt3/puddletag/source/puddlestuff/util.py", line 313, in write
    renamed = rename_file(audio, fn_fields)
  File "/home/x/github/pt3/puddletag/source/puddlestuff/util.py", line 201, in rename_file
    if rename_dir(audio.filepath, audio.dirpath, newdir):
  File "/home/x/github/pt3/puddletag/source/puddlestuff/util.py", line 90, in rename_dir
    raise DirRenameError(e, olddir, newdir)
puddlestuff.util.DirRenameError: [Errno 39] Directory not empty: '/mnt/sdb1/2tag/Copy (1) Blue Öyster Cult - 45th Anniversary Live in London [2444.1 kHz]'

```

**Comment by audiomuze** [comment]
Seem's it's pervasive to the error dialogue.  Triggered another error by deleting the underlying files and folders and then running the abovementioned action again:

![image](https://user-images.githubusercontent.com/6852511/90331432-83689d00-dfb4-11ea-8f90-10eac9a8b29e.png)
